name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - android-16.2
    paths-ignore:
      - '.github/**'
      - 'config/**'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -f build/Dockerfile -t surface-duo-aosp/treble .

      - name: Build ROM
        run: |
          mkdir -p builds
          docker run --rm \
                     --privileged \
                     --name treble \
                     --volume ${{ github.workspace }}/builds:/aosp/surface-duo-aosp/builds \
                     --volume ${{ github.workspace }}/signing-keys:/aosp/archfx-priv/keys \
                     --volume ${{ github.workspace }}/config/ota.json:/aosp/surface-duo-aosp/config/ota.json \
                     surface-duo-aosp/treble fullbuild

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: surface-duo-aosp-build
          path: builds/*.xz

  cleanup:
    needs: build
    runs-on: self-hosted
    if: ${{ always() }}
    steps:
      - name: Cleanup
        run: docker stop treble || true
